# Generated by Django 3.1.2 on 2020-11-17 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField(null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdf_file', models.FileField(upload_to='pdf_files')),
                ('image', models.ImageField(default='default_pdfImage.jpg', upload_to='pdf_images')),
                ('audio_file', models.FileField(null=True, upload_to='pdf_audios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
